import type { Product } from "@/components/product/product-card"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Noise ColorFit Pulse Grand Smartwatch with 1.69\" HD Display",
    brand: "Noise",
    description: "This smartwatch features a large 1.69\" HD display that delivers clear visuals and a smooth user experience for everyday use. It comes with active heart rate tracking, up to 7 days of battery life, and custom watch faces.",
    price: 525.00,
    oldPrice: 599.00,
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=500&q=80",
    images: [
      "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=500&q=80",
    ],
    rating: 4.5,
    gender: "women",
    display: "amoled",
    screen: "33-35",
    shape: "square",
    color: "rose-gold",
    discount: 12,
    tracking: ["gps", "heart-rate", "sleep"],
    battery: "7-days",
    bluetooth: "5.0",
    strap: "silicone",
    water: "ip68",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "2",
    name: "Noise Pulse Go Buzz Bluetooth Calling Smartwatch with 1.69\" TFT",
    brand: "Noise",
    description: "Make and receive calls directly from your wrist. Features a clear 1.69\" display, multiple sports modes, active sleep monitoring, and intelligent notification syncing.",
    price: 649.00,
    oldPrice: 799.00,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=500&q=80",
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=500&q=80",
    ],
    rating: 4.8,
    gender: "men",
    display: "analog-digital",
    screen: "33-35",
    shape: "rectangular",
    color: "black",
    discount: 18,
    tracking: ["spo2", "heart-rate", "sleep"],
    battery: "7-days",
    bluetooth: "calling",
    strap: "silicone",
    water: "ip68",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "3",
    name: "Noise ColorFit Pro 4 Advanced Smartwatch 60Hz AMOLED",
    brand: "Noise",
    description: "Premium smartwatch featuring a high-refresh rate 60Hz 1.72\" AMOLED screen, functional crown, advanced health tracking, and seamless Bluetooth calling.",
    price: 725.00,
    oldPrice: 899.00,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=500&q=80",
    rating: 4.2,
    gender: "women",
    display: "amoled",
    screen: "36-plus",
    shape: "rectangular",
    color: "blue",
    discount: 20,
    badge: "20% off",
    tracking: ["gps", "spo2", "heart-rate", "sleep"],
    battery: "14-days",
    bluetooth: "calling",
    strap: "metal",
    water: "5atm",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "4",
    name: "Apple Watch Series 9 GPS + Cellular 45mm Midnight Aluminium",
    brand: "Apple",
    description: "The ultimate device for a healthy life. Features advanced health sensors, crash detection, double tap gesture control, and a bright Always-On Retina display.",
    price: 1399.00,
    oldPrice: 1599.00,
    image: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=500&q=80",
    images: [
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=500&q=80",
    ],
    rating: 4.9,
    gender: "men",
    display: "amoled",
    screen: "36-plus",
    shape: "square",
    color: "black",
    discount: 12,
    tracking: ["gps", "spo2", "heart-rate", "sleep"],
    battery: "24-48",
    bluetooth: "5.3",
    strap: "silicone",
    water: "5atm",
    compatibility: ["ios"],
    collection: "electronics",
  },
  {
    id: "5",
    name: "Samsung Galaxy Watch6 Bluetooth 44mm Graphite Sport Band",
    brand: "Samsung",
    description: "Personalized fitness coaching, advanced sleep analysis, and a larger screen with a thinner bezel. Seamlessly integrates with your Galaxy ecosystem.",
    price: 925.00,
    oldPrice: 1049.00,
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=500&q=80",
    rating: 4.6,
    gender: "men",
    display: "amoled",
    screen: "36-plus",
    shape: "oval",
    color: "silver",
    discount: 11,
    badge: "New",
    tracking: ["gps", "spo2", "heart-rate", "sleep"],
    battery: "24-48",
    bluetooth: "5.3",
    strap: "silicone",
    water: "5atm",
    compatibility: ["android"],
    collection: "electronics",
  },
  {
    id: "6",
    name: "Xiaomi Watch S3 Bluetooth Classic Bezel Style",
    brand: "Xiaomi",
    description: "Distinctive round watch layout with interchangeable bezels, eSIM calling capabilities, dual-band GPS location tracking, and an outstanding 14-day battery life.",
    price: 525.00,
    oldPrice: 599.00,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=500&q=80",
    rating: 4.4,
    gender: "boys",
    display: "analog",
    screen: "36-plus",
    shape: "oval",
    color: "silver",
    discount: 12,
    tracking: ["gps", "heart-rate", "sleep"],
    battery: "14-days",
    bluetooth: "5.0",
    strap: "leather",
    water: "5atm",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "7",
    name: "Noise Icon 2 Fitness Tracker with Heart Rate Monitor",
    brand: "Noise",
    description: "Streamlined round display featuring multiple health monitoring trackers (SpO2, heart rate), 60+ sports modes, dynamic notifications, and long standby.",
    price: 725.00,
    oldPrice: 849.00,
    image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=500&q=80",
    rating: 4.1,
    gender: "girls",
    display: "analog",
    screen: "up-to-32",
    shape: "oval",
    color: "black",
    discount: 14,
    tracking: ["heart-rate", "sleep"],
    battery: "7-days",
    bluetooth: "5.0",
    strap: "silicone",
    water: "ip68",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "8",
    name: "Noise ColorFit Ultra 3 Premium Smartwatch Metallic Mesh Strap",
    brand: "Noise",
    description: "Superb 1.96\" AMOLED display with metallic strap, dynamic gesture support, stress indicator tracking, and a functional rotary crown.",
    price: 1125.00,
    oldPrice: 1499.00,
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    gender: "men",
    display: "amoled",
    screen: "36-plus",
    shape: "rectangular",
    color: "magenta",
    discount: 25,
    tracking: ["gps", "spo2", "heart-rate", "sleep"],
    battery: "7-days",
    bluetooth: "calling",
    strap: "metal",
    water: "ip68",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "9",
    name: "Apple Watch SE (2nd Gen) GPS 40mm Starlight Sport Band",
    brand: "Apple",
    description: "All the essentials to stay motivated and active, monitor your health, connect easily, and keep safe with crash detection and emergency SOS.",
    price: 825.00,
    oldPrice: 949.00,
    image: "https://images.unsplash.com/photo-1517502884422-41eaaced0168?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    gender: "women",
    display: "amoled",
    screen: "up-to-32",
    shape: "rectangular",
    color: "rose-gold",
    discount: 13,
    tracking: ["gps", "spo2", "heart-rate", "sleep"],
    battery: "24-48",
    bluetooth: "5.3",
    strap: "silicone",
    water: "5atm",
    compatibility: ["ios"],
    collection: "electronics",
  },
  {
    id: "10",
    name: "Samsung Galaxy Watch FE 40mm Pink Gold Active tracking",
    brand: "Samsung",
    description: "Designed to keep you on track. Features premium aluminum build, optical heart rate sensor, body composition index analysis, and customizable bands.",
    price: 525.00,
    oldPrice: 599.00,
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=500&q=80",
    rating: 4.3,
    gender: "girls",
    display: "amoled",
    screen: "up-to-32",
    shape: "oval",
    color: "orange",
    discount: 12,
    badge: "New",
    tracking: ["gps", "heart-rate", "sleep"],
    battery: "24-48",
    bluetooth: "5.0",
    strap: "silicone",
    water: "5atm",
    compatibility: ["android"],
    collection: "electronics",
  },
  {
    id: "11",
    name: "Xiaomi Redmi Watch 4 AMOLED Bluetooth Calling GPS",
    brand: "Xiaomi",
    description: "Huge 1.97\" AMOLED display with metal frame bezel, standalone GNSS five-system positioning, all-day oxygen saturation tracker, and 20-day battery backup.",
    price: 1125.00,
    oldPrice: 1299.00,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=500&q=80",
    rating: 4.5,
    gender: "men",
    display: "amoled",
    screen: "36-plus",
    shape: "square",
    color: "silver",
    discount: 13,
    tracking: ["gps", "spo2", "heart-rate", "sleep"],
    battery: "14-days",
    bluetooth: "calling",
    strap: "silicone",
    water: "ip68",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "12",
    name: "Noise Loop Buzz Smartwatch with SpO2 and Heart Rate Monitor",
    brand: "Noise",
    description: "A compact budget watch packed with features. Real-time SpO2 tracker, heart rate monitor, smart sedentary reminders, and custom color straps.",
    price: 525.00,
    oldPrice: 649.00,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=500&q=80",
    rating: 4.0,
    gender: "boys",
    display: "analog-digital",
    screen: "up-to-32",
    shape: "rectangular",
    color: "purple",
    discount: 19,
    badge: "20% off",
    tracking: ["spo2", "heart-rate"],
    battery: "7-days",
    bluetooth: "5.0",
    strap: "silicone",
    water: "ip68",
    compatibility: ["ios", "android"],
    collection: "electronics",
  },
  {
    id: "13",
    name: "Organic Vitamin C Brightening Serum with Hyaluronic Acid",
    brand: "GlowLab",
    description: "A powerful antioxidant serum that brightens skin, reduces dark spots, and boosts collagen production. Formulated with 20% Vitamin C, hyaluronic acid, and vitamin E for a radiant complexion.",
    price: 45.00,
    oldPrice: 59.00,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=500&q=80",
    ],
    rating: 4.7,
    gender: "women",
    display: "",
    screen: "",
    shape: "",
    color: "gold",
    discount: 24,
    badge: "Popular",
    collection: "beauty",
  },
  {
    id: "14",
    name: "Hydrating Facial Moisturizer with SPF 50 Sunscreen",
    brand: "DermaCare",
    description: "A lightweight daily moisturizer that provides broad-spectrum SPF 50 protection while deeply hydrating the skin. Non-greasy formula suitable for all skin types.",
    price: 38.00,
    oldPrice: 48.00,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=500&q=80",
    rating: 4.5,
    gender: "women",
    display: "",
    screen: "",
    shape: "",
    color: "white",
    discount: 21,
    collection: "beauty",
  },
  {
    id: "15",
    name: "Professional Makeup Brush Set - 12 Pieces with Case",
    brand: "LuxeBeauty",
    description: "Complete set of 12 professional-grade makeup brushes including foundation, powder, eyeshadow, blending, and lip brushes. Ultra-soft synthetic bristles in a premium travel case.",
    price: 52.00,
    oldPrice: 72.00,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=500&q=80",
    rating: 4.8,
    gender: "women",
    display: "",
    screen: "",
    shape: "",
    color: "black",
    discount: 28,
    badge: "New",
    collection: "beauty",
  },
  {
    id: "16",
    name: "Retinol Anti-Aging Night Cream with Peptides",
    brand: "SkinElite",
    description: "Advanced night cream with encapsulated retinol, peptides, and ceramides that reduces fine lines and wrinkles while you sleep. Dermatologist tested for sensitive skin.",
    price: 65.00,
    oldPrice: 85.00,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=500&q=80",
    rating: 4.4,
    gender: "women",
    display: "",
    screen: "",
    shape: "",
    color: "gold",
    discount: 24,
    collection: "beauty",
  },
  {
    id: "17",
    name: "Classic Fit Cotton T-Shirt - Premium Quality",
    brand: "EssentialWear",
    description: "Crafted from 100% organic ring-spun cotton for ultimate comfort. Features a classic fit, reinforced seams, and a comfortable ribbed collar. Available in multiple colors.",
    price: 29.00,
    oldPrice: 39.00,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=500&q=80",
    rating: 4.6,
    gender: "men",
    display: "",
    screen: "",
    shape: "",
    color: "white",
    discount: 26,
    badge: "Popular",
    collection: "clothing",
  },
  {
    id: "18",
    name: "Slim Fit Stretch Denim Jeans with Modern Taper",
    brand: "DenimCo",
    description: "Modern slim fit jeans crafted from premium stretch denim for all-day comfort. Features a mid-rise waist, tapered leg, and classic five-pocket styling.",
    price: 69.00,
    oldPrice: 89.00,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=500&q=80",
    rating: 4.3,
    gender: "men",
    display: "",
    screen: "",
    shape: "",
    color: "blue",
    discount: 22,
    collection: "clothing",
  },
  {
    id: "19",
    name: "Floral Summer Maxi Dress with Adjustable Straps",
    brand: "VelvetRose",
    description: "A breezy maxi dress featuring an all-over floral print, adjustable spaghetti straps, and a flattering A-line silhouette. Made from lightweight, breathable fabric perfect for summer.",
    price: 59.00,
    oldPrice: 79.00,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=500&q=80",
    rating: 4.7,
    gender: "women",
    display: "",
    screen: "",
    shape: "",
    color: "magenta",
    discount: 25,
    badge: "New",
    collection: "clothing",
  },
  {
    id: "20",
    name: "Waterproof Puffer Jacket with Thermal Lining",
    brand: "OutdoorPro",
    description: "Stay warm and dry with this waterproof puffer jacket featuring thermal insulation, a detachable hood, and multiple zippered pockets. Ideal for outdoor activities in cold weather.",
    price: 89.00,
    oldPrice: 119.00,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=500&q=80",
    rating: 4.5,
    gender: "men",
    display: "",
    screen: "",
    shape: "",
    color: "black",
    discount: 25,
    collection: "clothing",
  },
]
