/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MainUsersIndexRouteImport } from './routes/_main/users/index'
import { Route as MainTiersIndexRouteImport } from './routes/_main/tiers/index'
import { Route as MainTicketsIndexRouteImport } from './routes/_main/tickets/index'
import { Route as MainSupervisorsIndexRouteImport } from './routes/_main/supervisors/index'
import { Route as MainStaticPagesIndexRouteImport } from './routes/_main/static-pages/index'
import { Route as MainSmsProvidersIndexRouteImport } from './routes/_main/sms-providers/index'
import { Route as MainSlidersIndexRouteImport } from './routes/_main/sliders/index'
import { Route as MainShowRoomsIndexRouteImport } from './routes/_main/show-rooms/index'
import { Route as MainRolesIndexRouteImport } from './routes/_main/roles/index'
import { Route as MainRewardsIndexRouteImport } from './routes/_main/rewards/index'
import { Route as MainReviewsIndexRouteImport } from './routes/_main/reviews/index'
import { Route as MainReturnsIndexRouteImport } from './routes/_main/returns/index'
import { Route as MainProfileIndexRouteImport } from './routes/_main/profile/index'
import { Route as MainProductsIndexRouteImport } from './routes/_main/products/index'
import { Route as MainPaymentGatewaysIndexRouteImport } from './routes/_main/payment-gateways/index'
import { Route as MainOrdersIndexRouteImport } from './routes/_main/orders/index'
import { Route as MainOffersIndexRouteImport } from './routes/_main/offers/index'
import { Route as MainMessagesIndexRouteImport } from './routes/_main/messages/index'
import { Route as MainMessageTemplatesIndexRouteImport } from './routes/_main/message-templates/index'
import { Route as MainFaqsIndexRouteImport } from './routes/_main/faqs/index'
import { Route as MainExchangesIndexRouteImport } from './routes/_main/exchanges/index'
import { Route as MainEarningRulesIndexRouteImport } from './routes/_main/earning-rules/index'
import { Route as MainCouponsIndexRouteImport } from './routes/_main/coupons/index'
import { Route as MainCategoriesIndexRouteImport } from './routes/_main/categories/index'
import { Route as MainAttributesIndexRouteImport } from './routes/_main/attributes/index'
import { Route as MainAdminNotificationsIndexRouteImport } from './routes/_main/admin-notifications/index'
import { Route as MainTiersAddRouteImport } from './routes/_main/tiers/add'
import { Route as MainSupervisorsAddRouteImport } from './routes/_main/supervisors/add'
import { Route as MainStaticPagesAddRouteImport } from './routes/_main/static-pages/add'
import { Route as MainSlidersAddRouteImport } from './routes/_main/sliders/add'
import { Route as MainShowRoomsAddRouteImport } from './routes/_main/show-rooms/add'
import { Route as MainRolesAddRouteImport } from './routes/_main/roles/add'
import { Route as MainRewardsAddRouteImport } from './routes/_main/rewards/add'
import { Route as MainProductsAddRouteImport } from './routes/_main/products/add'
import { Route as MainOffersAddRouteImport } from './routes/_main/offers/add'
import { Route as MainMessagesSendRouteImport } from './routes/_main/messages/send'
import { Route as MainMessageTemplatesAddRouteImport } from './routes/_main/message-templates/add'
import { Route as MainFaqsAddRouteImport } from './routes/_main/faqs/add'
import { Route as MainEarningRulesAddRouteImport } from './routes/_main/earning-rules/add'
import { Route as MainCouponsAddRouteImport } from './routes/_main/coupons/add'
import { Route as MainCategoriesAddRouteImport } from './routes/_main/categories/add'
import { Route as MainAttributesAddRouteImport } from './routes/_main/attributes/add'
import { Route as MainSettingsShopifyStoresIndexRouteImport } from './routes/_main/settings/shopify-stores/index'
import { Route as MainSettingsNotificationsIndexRouteImport } from './routes/_main/settings/notifications/index'
import { Route as MainSettingsGeneralIndexRouteImport } from './routes/_main/settings/general/index'
import { Route as MainSettingsCountriesIndexRouteImport } from './routes/_main/settings/countries/index'
import { Route as MainSettingsCitiesIndexRouteImport } from './routes/_main/settings/cities/index'
import { Route as MainAttributesValuesIndexRouteImport } from './routes/_main/attributes/values/index'
import { Route as MainUsersShowIdRouteImport } from './routes/_main/users/show/$id'
import { Route as MainTiersEditIdRouteImport } from './routes/_main/tiers/edit/$id'
import { Route as MainTicketsShowIdRouteImport } from './routes/_main/tickets/show/$id'
import { Route as MainSupervisorsEditIdRouteImport } from './routes/_main/supervisors/edit/$id'
import { Route as MainStaticPagesShowIdRouteImport } from './routes/_main/static-pages/show/$id'
import { Route as MainStaticPagesEditIdRouteImport } from './routes/_main/static-pages/edit/$id'
import { Route as MainSmsProvidersSessionsIdRouteImport } from './routes/_main/sms-providers/sessions/$id'
import { Route as MainSlidersEditIdRouteImport } from './routes/_main/sliders/edit/$id'
import { Route as MainShowRoomsEditIdRouteImport } from './routes/_main/show-rooms/edit/$id'
import { Route as MainSettingsShopifyStoresAddRouteImport } from './routes/_main/settings/shopify-stores/add'
import { Route as MainSettingsCountriesAddRouteImport } from './routes/_main/settings/countries/add'
import { Route as MainSettingsCitiesAddRouteImport } from './routes/_main/settings/cities/add'
import { Route as MainRolesShowIdRouteImport } from './routes/_main/roles/show/$id'
import { Route as MainRolesEditIdRouteImport } from './routes/_main/roles/edit/$id'
import { Route as MainRewardsEditIdRouteImport } from './routes/_main/rewards/edit/$id'
import { Route as MainReviewsShowIdRouteImport } from './routes/_main/reviews/show/$id'
import { Route as MainProductsShowIdRouteImport } from './routes/_main/products/show/$id'
import { Route as MainProductsEditIdRouteImport } from './routes/_main/products/edit/$id'
import { Route as MainPaymentGatewaysSessionsIdRouteImport } from './routes/_main/payment-gateways/sessions/$id'
import { Route as MainOrdersShowIdRouteImport } from './routes/_main/orders/show/$id'
import { Route as MainOffersEditIdRouteImport } from './routes/_main/offers/edit/$id'
import { Route as MainMessagesShowIdRouteImport } from './routes/_main/messages/show/$id'
import { Route as MainMessageTemplatesShowIdRouteImport } from './routes/_main/message-templates/show/$id'
import { Route as MainMessageTemplatesEditIdRouteImport } from './routes/_main/message-templates/edit/$id'
import { Route as MainFaqsEditIdRouteImport } from './routes/_main/faqs/edit/$id'
import { Route as MainEarningRulesEditIdRouteImport } from './routes/_main/earning-rules/edit/$id'
import { Route as MainCouponsEditIdRouteImport } from './routes/_main/coupons/edit/$id'
import { Route as MainCategoriesShowIdRouteImport } from './routes/_main/categories/show/$id'
import { Route as MainCategoriesEditIdRouteImport } from './routes/_main/categories/edit/$id'
import { Route as MainAttributesValuesAddRouteImport } from './routes/_main/attributes/values/add'
import { Route as MainAttributesShowIdRouteImport } from './routes/_main/attributes/show/$id'
import { Route as MainAttributesEditIdRouteImport } from './routes/_main/attributes/edit/$id'
import { Route as MainAdminNotificationsShowIdRouteImport } from './routes/_main/admin-notifications/show/$id'
import { Route as MainSettingsShopifyStoresShowIdRouteImport } from './routes/_main/settings/shopify-stores/show/$id'
import { Route as MainSettingsShopifyStoresEditIdRouteImport } from './routes/_main/settings/shopify-stores/edit/$id'
import { Route as MainSettingsCountriesShowIdRouteImport } from './routes/_main/settings/countries/show/$id'
import { Route as MainSettingsCountriesEditIdRouteImport } from './routes/_main/settings/countries/edit/$id'
import { Route as MainSettingsCitiesEditIdRouteImport } from './routes/_main/settings/cities/edit/$id'
import { Route as MainAttributesValuesEditIdRouteImport } from './routes/_main/attributes/values/edit/$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainUsersIndexRoute = MainUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTiersIndexRoute = MainTiersIndexRouteImport.update({
  id: '/tiers/',
  path: '/tiers/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTicketsIndexRoute = MainTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSupervisorsIndexRoute = MainSupervisorsIndexRouteImport.update({
  id: '/supervisors/',
  path: '/supervisors/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStaticPagesIndexRoute = MainStaticPagesIndexRouteImport.update({
  id: '/static-pages/',
  path: '/static-pages/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSmsProvidersIndexRoute = MainSmsProvidersIndexRouteImport.update({
  id: '/sms-providers/',
  path: '/sms-providers/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSlidersIndexRoute = MainSlidersIndexRouteImport.update({
  id: '/sliders/',
  path: '/sliders/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainShowRoomsIndexRoute = MainShowRoomsIndexRouteImport.update({
  id: '/show-rooms/',
  path: '/show-rooms/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRolesIndexRoute = MainRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRewardsIndexRoute = MainRewardsIndexRouteImport.update({
  id: '/rewards/',
  path: '/rewards/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainReviewsIndexRoute = MainReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainReturnsIndexRoute = MainReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsIndexRoute = MainProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPaymentGatewaysIndexRoute =
  MainPaymentGatewaysIndexRouteImport.update({
    id: '/payment-gateways/',
    path: '/payment-gateways/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersIndexRoute = MainOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOffersIndexRoute = MainOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMessagesIndexRoute = MainMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMessageTemplatesIndexRoute =
  MainMessageTemplatesIndexRouteImport.update({
    id: '/message-templates/',
    path: '/message-templates/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainFaqsIndexRoute = MainFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainExchangesIndexRoute = MainExchangesIndexRouteImport.update({
  id: '/exchanges/',
  path: '/exchanges/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEarningRulesIndexRoute = MainEarningRulesIndexRouteImport.update({
  id: '/earning-rules/',
  path: '/earning-rules/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCouponsIndexRoute = MainCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesIndexRoute = MainCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAttributesIndexRoute = MainAttributesIndexRouteImport.update({
  id: '/attributes/',
  path: '/attributes/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminNotificationsIndexRoute =
  MainAdminNotificationsIndexRouteImport.update({
    id: '/admin-notifications/',
    path: '/admin-notifications/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainTiersAddRoute = MainTiersAddRouteImport.update({
  id: '/tiers/add',
  path: '/tiers/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSupervisorsAddRoute = MainSupervisorsAddRouteImport.update({
  id: '/supervisors/add',
  path: '/supervisors/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStaticPagesAddRoute = MainStaticPagesAddRouteImport.update({
  id: '/static-pages/add',
  path: '/static-pages/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSlidersAddRoute = MainSlidersAddRouteImport.update({
  id: '/sliders/add',
  path: '/sliders/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainShowRoomsAddRoute = MainShowRoomsAddRouteImport.update({
  id: '/show-rooms/add',
  path: '/show-rooms/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRolesAddRoute = MainRolesAddRouteImport.update({
  id: '/roles/add',
  path: '/roles/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRewardsAddRoute = MainRewardsAddRouteImport.update({
  id: '/rewards/add',
  path: '/rewards/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsAddRoute = MainProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOffersAddRoute = MainOffersAddRouteImport.update({
  id: '/offers/add',
  path: '/offers/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMessagesSendRoute = MainMessagesSendRouteImport.update({
  id: '/messages/send',
  path: '/messages/send',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMessageTemplatesAddRoute = MainMessageTemplatesAddRouteImport.update({
  id: '/message-templates/add',
  path: '/message-templates/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFaqsAddRoute = MainFaqsAddRouteImport.update({
  id: '/faqs/add',
  path: '/faqs/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEarningRulesAddRoute = MainEarningRulesAddRouteImport.update({
  id: '/earning-rules/add',
  path: '/earning-rules/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCouponsAddRoute = MainCouponsAddRouteImport.update({
  id: '/coupons/add',
  path: '/coupons/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesAddRoute = MainCategoriesAddRouteImport.update({
  id: '/categories/add',
  path: '/categories/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAttributesAddRoute = MainAttributesAddRouteImport.update({
  id: '/attributes/add',
  path: '/attributes/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsShopifyStoresIndexRoute =
  MainSettingsShopifyStoresIndexRouteImport.update({
    id: '/settings/shopify-stores/',
    path: '/settings/shopify-stores/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsNotificationsIndexRoute =
  MainSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsGeneralIndexRoute =
  MainSettingsGeneralIndexRouteImport.update({
    id: '/settings/general/',
    path: '/settings/general/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCountriesIndexRoute =
  MainSettingsCountriesIndexRouteImport.update({
    id: '/settings/countries/',
    path: '/settings/countries/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCitiesIndexRoute = MainSettingsCitiesIndexRouteImport.update({
  id: '/settings/cities/',
  path: '/settings/cities/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAttributesValuesIndexRoute =
  MainAttributesValuesIndexRouteImport.update({
    id: '/attributes/values/',
    path: '/attributes/values/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainUsersShowIdRoute = MainUsersShowIdRouteImport.update({
  id: '/users/show/$id',
  path: '/users/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTiersEditIdRoute = MainTiersEditIdRouteImport.update({
  id: '/tiers/edit/$id',
  path: '/tiers/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTicketsShowIdRoute = MainTicketsShowIdRouteImport.update({
  id: '/tickets/show/$id',
  path: '/tickets/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSupervisorsEditIdRoute = MainSupervisorsEditIdRouteImport.update({
  id: '/supervisors/edit/$id',
  path: '/supervisors/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStaticPagesShowIdRoute = MainStaticPagesShowIdRouteImport.update({
  id: '/static-pages/show/$id',
  path: '/static-pages/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStaticPagesEditIdRoute = MainStaticPagesEditIdRouteImport.update({
  id: '/static-pages/edit/$id',
  path: '/static-pages/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSmsProvidersSessionsIdRoute =
  MainSmsProvidersSessionsIdRouteImport.update({
    id: '/sms-providers/sessions/$id',
    path: '/sms-providers/sessions/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSlidersEditIdRoute = MainSlidersEditIdRouteImport.update({
  id: '/sliders/edit/$id',
  path: '/sliders/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainShowRoomsEditIdRoute = MainShowRoomsEditIdRouteImport.update({
  id: '/show-rooms/edit/$id',
  path: '/show-rooms/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsShopifyStoresAddRoute =
  MainSettingsShopifyStoresAddRouteImport.update({
    id: '/settings/shopify-stores/add',
    path: '/settings/shopify-stores/add',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCountriesAddRoute =
  MainSettingsCountriesAddRouteImport.update({
    id: '/settings/countries/add',
    path: '/settings/countries/add',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCitiesAddRoute = MainSettingsCitiesAddRouteImport.update({
  id: '/settings/cities/add',
  path: '/settings/cities/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRolesShowIdRoute = MainRolesShowIdRouteImport.update({
  id: '/roles/show/$id',
  path: '/roles/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRolesEditIdRoute = MainRolesEditIdRouteImport.update({
  id: '/roles/edit/$id',
  path: '/roles/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRewardsEditIdRoute = MainRewardsEditIdRouteImport.update({
  id: '/rewards/edit/$id',
  path: '/rewards/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainReviewsShowIdRoute = MainReviewsShowIdRouteImport.update({
  id: '/reviews/show/$id',
  path: '/reviews/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsShowIdRoute = MainProductsShowIdRouteImport.update({
  id: '/products/show/$id',
  path: '/products/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsEditIdRoute = MainProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPaymentGatewaysSessionsIdRoute =
  MainPaymentGatewaysSessionsIdRouteImport.update({
    id: '/payment-gateways/sessions/$id',
    path: '/payment-gateways/sessions/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersShowIdRoute = MainOrdersShowIdRouteImport.update({
  id: '/orders/show/$id',
  path: '/orders/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOffersEditIdRoute = MainOffersEditIdRouteImport.update({
  id: '/offers/edit/$id',
  path: '/offers/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMessagesShowIdRoute = MainMessagesShowIdRouteImport.update({
  id: '/messages/show/$id',
  path: '/messages/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMessageTemplatesShowIdRoute =
  MainMessageTemplatesShowIdRouteImport.update({
    id: '/message-templates/show/$id',
    path: '/message-templates/show/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainMessageTemplatesEditIdRoute =
  MainMessageTemplatesEditIdRouteImport.update({
    id: '/message-templates/edit/$id',
    path: '/message-templates/edit/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainFaqsEditIdRoute = MainFaqsEditIdRouteImport.update({
  id: '/faqs/edit/$id',
  path: '/faqs/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEarningRulesEditIdRoute = MainEarningRulesEditIdRouteImport.update({
  id: '/earning-rules/edit/$id',
  path: '/earning-rules/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCouponsEditIdRoute = MainCouponsEditIdRouteImport.update({
  id: '/coupons/edit/$id',
  path: '/coupons/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesShowIdRoute = MainCategoriesShowIdRouteImport.update({
  id: '/categories/show/$id',
  path: '/categories/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesEditIdRoute = MainCategoriesEditIdRouteImport.update({
  id: '/categories/edit/$id',
  path: '/categories/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAttributesValuesAddRoute = MainAttributesValuesAddRouteImport.update({
  id: '/attributes/values/add',
  path: '/attributes/values/add',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAttributesShowIdRoute = MainAttributesShowIdRouteImport.update({
  id: '/attributes/show/$id',
  path: '/attributes/show/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAttributesEditIdRoute = MainAttributesEditIdRouteImport.update({
  id: '/attributes/edit/$id',
  path: '/attributes/edit/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminNotificationsShowIdRoute =
  MainAdminNotificationsShowIdRouteImport.update({
    id: '/admin-notifications/show/$id',
    path: '/admin-notifications/show/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsShopifyStoresShowIdRoute =
  MainSettingsShopifyStoresShowIdRouteImport.update({
    id: '/settings/shopify-stores/show/$id',
    path: '/settings/shopify-stores/show/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsShopifyStoresEditIdRoute =
  MainSettingsShopifyStoresEditIdRouteImport.update({
    id: '/settings/shopify-stores/edit/$id',
    path: '/settings/shopify-stores/edit/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCountriesShowIdRoute =
  MainSettingsCountriesShowIdRouteImport.update({
    id: '/settings/countries/show/$id',
    path: '/settings/countries/show/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCountriesEditIdRoute =
  MainSettingsCountriesEditIdRouteImport.update({
    id: '/settings/countries/edit/$id',
    path: '/settings/countries/edit/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsCitiesEditIdRoute =
  MainSettingsCitiesEditIdRouteImport.update({
    id: '/settings/cities/edit/$id',
    path: '/settings/cities/edit/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainAttributesValuesEditIdRoute =
  MainAttributesValuesEditIdRouteImport.update({
    id: '/attributes/values/edit/$id',
    path: '/attributes/values/edit/$id',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/attributes/add': typeof MainAttributesAddRoute
  '/categories/add': typeof MainCategoriesAddRoute
  '/coupons/add': typeof MainCouponsAddRoute
  '/earning-rules/add': typeof MainEarningRulesAddRoute
  '/faqs/add': typeof MainFaqsAddRoute
  '/message-templates/add': typeof MainMessageTemplatesAddRoute
  '/messages/send': typeof MainMessagesSendRoute
  '/offers/add': typeof MainOffersAddRoute
  '/products/add': typeof MainProductsAddRoute
  '/rewards/add': typeof MainRewardsAddRoute
  '/roles/add': typeof MainRolesAddRoute
  '/show-rooms/add': typeof MainShowRoomsAddRoute
  '/sliders/add': typeof MainSlidersAddRoute
  '/static-pages/add': typeof MainStaticPagesAddRoute
  '/supervisors/add': typeof MainSupervisorsAddRoute
  '/tiers/add': typeof MainTiersAddRoute
  '/admin-notifications/': typeof MainAdminNotificationsIndexRoute
  '/attributes/': typeof MainAttributesIndexRoute
  '/categories/': typeof MainCategoriesIndexRoute
  '/coupons/': typeof MainCouponsIndexRoute
  '/earning-rules/': typeof MainEarningRulesIndexRoute
  '/exchanges/': typeof MainExchangesIndexRoute
  '/faqs/': typeof MainFaqsIndexRoute
  '/message-templates/': typeof MainMessageTemplatesIndexRoute
  '/messages/': typeof MainMessagesIndexRoute
  '/offers/': typeof MainOffersIndexRoute
  '/orders/': typeof MainOrdersIndexRoute
  '/payment-gateways/': typeof MainPaymentGatewaysIndexRoute
  '/products/': typeof MainProductsIndexRoute
  '/profile/': typeof MainProfileIndexRoute
  '/returns/': typeof MainReturnsIndexRoute
  '/reviews/': typeof MainReviewsIndexRoute
  '/rewards/': typeof MainRewardsIndexRoute
  '/roles/': typeof MainRolesIndexRoute
  '/show-rooms/': typeof MainShowRoomsIndexRoute
  '/sliders/': typeof MainSlidersIndexRoute
  '/sms-providers/': typeof MainSmsProvidersIndexRoute
  '/static-pages/': typeof MainStaticPagesIndexRoute
  '/supervisors/': typeof MainSupervisorsIndexRoute
  '/tickets/': typeof MainTicketsIndexRoute
  '/tiers/': typeof MainTiersIndexRoute
  '/users/': typeof MainUsersIndexRoute
  '/admin-notifications/show/$id': typeof MainAdminNotificationsShowIdRoute
  '/attributes/edit/$id': typeof MainAttributesEditIdRoute
  '/attributes/show/$id': typeof MainAttributesShowIdRoute
  '/attributes/values/add': typeof MainAttributesValuesAddRoute
  '/categories/edit/$id': typeof MainCategoriesEditIdRoute
  '/categories/show/$id': typeof MainCategoriesShowIdRoute
  '/coupons/edit/$id': typeof MainCouponsEditIdRoute
  '/earning-rules/edit/$id': typeof MainEarningRulesEditIdRoute
  '/faqs/edit/$id': typeof MainFaqsEditIdRoute
  '/message-templates/edit/$id': typeof MainMessageTemplatesEditIdRoute
  '/message-templates/show/$id': typeof MainMessageTemplatesShowIdRoute
  '/messages/show/$id': typeof MainMessagesShowIdRoute
  '/offers/edit/$id': typeof MainOffersEditIdRoute
  '/orders/show/$id': typeof MainOrdersShowIdRoute
  '/payment-gateways/sessions/$id': typeof MainPaymentGatewaysSessionsIdRoute
  '/products/edit/$id': typeof MainProductsEditIdRoute
  '/products/show/$id': typeof MainProductsShowIdRoute
  '/reviews/show/$id': typeof MainReviewsShowIdRoute
  '/rewards/edit/$id': typeof MainRewardsEditIdRoute
  '/roles/edit/$id': typeof MainRolesEditIdRoute
  '/roles/show/$id': typeof MainRolesShowIdRoute
  '/settings/cities/add': typeof MainSettingsCitiesAddRoute
  '/settings/countries/add': typeof MainSettingsCountriesAddRoute
  '/settings/shopify-stores/add': typeof MainSettingsShopifyStoresAddRoute
  '/show-rooms/edit/$id': typeof MainShowRoomsEditIdRoute
  '/sliders/edit/$id': typeof MainSlidersEditIdRoute
  '/sms-providers/sessions/$id': typeof MainSmsProvidersSessionsIdRoute
  '/static-pages/edit/$id': typeof MainStaticPagesEditIdRoute
  '/static-pages/show/$id': typeof MainStaticPagesShowIdRoute
  '/supervisors/edit/$id': typeof MainSupervisorsEditIdRoute
  '/tickets/show/$id': typeof MainTicketsShowIdRoute
  '/tiers/edit/$id': typeof MainTiersEditIdRoute
  '/users/show/$id': typeof MainUsersShowIdRoute
  '/attributes/values/': typeof MainAttributesValuesIndexRoute
  '/settings/cities/': typeof MainSettingsCitiesIndexRoute
  '/settings/countries/': typeof MainSettingsCountriesIndexRoute
  '/settings/general/': typeof MainSettingsGeneralIndexRoute
  '/settings/notifications/': typeof MainSettingsNotificationsIndexRoute
  '/settings/shopify-stores/': typeof MainSettingsShopifyStoresIndexRoute
  '/attributes/values/edit/$id': typeof MainAttributesValuesEditIdRoute
  '/settings/cities/edit/$id': typeof MainSettingsCitiesEditIdRoute
  '/settings/countries/edit/$id': typeof MainSettingsCountriesEditIdRoute
  '/settings/countries/show/$id': typeof MainSettingsCountriesShowIdRoute
  '/settings/shopify-stores/edit/$id': typeof MainSettingsShopifyStoresEditIdRoute
  '/settings/shopify-stores/show/$id': typeof MainSettingsShopifyStoresShowIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof MainIndexRoute
  '/attributes/add': typeof MainAttributesAddRoute
  '/categories/add': typeof MainCategoriesAddRoute
  '/coupons/add': typeof MainCouponsAddRoute
  '/earning-rules/add': typeof MainEarningRulesAddRoute
  '/faqs/add': typeof MainFaqsAddRoute
  '/message-templates/add': typeof MainMessageTemplatesAddRoute
  '/messages/send': typeof MainMessagesSendRoute
  '/offers/add': typeof MainOffersAddRoute
  '/products/add': typeof MainProductsAddRoute
  '/rewards/add': typeof MainRewardsAddRoute
  '/roles/add': typeof MainRolesAddRoute
  '/show-rooms/add': typeof MainShowRoomsAddRoute
  '/sliders/add': typeof MainSlidersAddRoute
  '/static-pages/add': typeof MainStaticPagesAddRoute
  '/supervisors/add': typeof MainSupervisorsAddRoute
  '/tiers/add': typeof MainTiersAddRoute
  '/admin-notifications': typeof MainAdminNotificationsIndexRoute
  '/attributes': typeof MainAttributesIndexRoute
  '/categories': typeof MainCategoriesIndexRoute
  '/coupons': typeof MainCouponsIndexRoute
  '/earning-rules': typeof MainEarningRulesIndexRoute
  '/exchanges': typeof MainExchangesIndexRoute
  '/faqs': typeof MainFaqsIndexRoute
  '/message-templates': typeof MainMessageTemplatesIndexRoute
  '/messages': typeof MainMessagesIndexRoute
  '/offers': typeof MainOffersIndexRoute
  '/orders': typeof MainOrdersIndexRoute
  '/payment-gateways': typeof MainPaymentGatewaysIndexRoute
  '/products': typeof MainProductsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/returns': typeof MainReturnsIndexRoute
  '/reviews': typeof MainReviewsIndexRoute
  '/rewards': typeof MainRewardsIndexRoute
  '/roles': typeof MainRolesIndexRoute
  '/show-rooms': typeof MainShowRoomsIndexRoute
  '/sliders': typeof MainSlidersIndexRoute
  '/sms-providers': typeof MainSmsProvidersIndexRoute
  '/static-pages': typeof MainStaticPagesIndexRoute
  '/supervisors': typeof MainSupervisorsIndexRoute
  '/tickets': typeof MainTicketsIndexRoute
  '/tiers': typeof MainTiersIndexRoute
  '/users': typeof MainUsersIndexRoute
  '/admin-notifications/show/$id': typeof MainAdminNotificationsShowIdRoute
  '/attributes/edit/$id': typeof MainAttributesEditIdRoute
  '/attributes/show/$id': typeof MainAttributesShowIdRoute
  '/attributes/values/add': typeof MainAttributesValuesAddRoute
  '/categories/edit/$id': typeof MainCategoriesEditIdRoute
  '/categories/show/$id': typeof MainCategoriesShowIdRoute
  '/coupons/edit/$id': typeof MainCouponsEditIdRoute
  '/earning-rules/edit/$id': typeof MainEarningRulesEditIdRoute
  '/faqs/edit/$id': typeof MainFaqsEditIdRoute
  '/message-templates/edit/$id': typeof MainMessageTemplatesEditIdRoute
  '/message-templates/show/$id': typeof MainMessageTemplatesShowIdRoute
  '/messages/show/$id': typeof MainMessagesShowIdRoute
  '/offers/edit/$id': typeof MainOffersEditIdRoute
  '/orders/show/$id': typeof MainOrdersShowIdRoute
  '/payment-gateways/sessions/$id': typeof MainPaymentGatewaysSessionsIdRoute
  '/products/edit/$id': typeof MainProductsEditIdRoute
  '/products/show/$id': typeof MainProductsShowIdRoute
  '/reviews/show/$id': typeof MainReviewsShowIdRoute
  '/rewards/edit/$id': typeof MainRewardsEditIdRoute
  '/roles/edit/$id': typeof MainRolesEditIdRoute
  '/roles/show/$id': typeof MainRolesShowIdRoute
  '/settings/cities/add': typeof MainSettingsCitiesAddRoute
  '/settings/countries/add': typeof MainSettingsCountriesAddRoute
  '/settings/shopify-stores/add': typeof MainSettingsShopifyStoresAddRoute
  '/show-rooms/edit/$id': typeof MainShowRoomsEditIdRoute
  '/sliders/edit/$id': typeof MainSlidersEditIdRoute
  '/sms-providers/sessions/$id': typeof MainSmsProvidersSessionsIdRoute
  '/static-pages/edit/$id': typeof MainStaticPagesEditIdRoute
  '/static-pages/show/$id': typeof MainStaticPagesShowIdRoute
  '/supervisors/edit/$id': typeof MainSupervisorsEditIdRoute
  '/tickets/show/$id': typeof MainTicketsShowIdRoute
  '/tiers/edit/$id': typeof MainTiersEditIdRoute
  '/users/show/$id': typeof MainUsersShowIdRoute
  '/attributes/values': typeof MainAttributesValuesIndexRoute
  '/settings/cities': typeof MainSettingsCitiesIndexRoute
  '/settings/countries': typeof MainSettingsCountriesIndexRoute
  '/settings/general': typeof MainSettingsGeneralIndexRoute
  '/settings/notifications': typeof MainSettingsNotificationsIndexRoute
  '/settings/shopify-stores': typeof MainSettingsShopifyStoresIndexRoute
  '/attributes/values/edit/$id': typeof MainAttributesValuesEditIdRoute
  '/settings/cities/edit/$id': typeof MainSettingsCitiesEditIdRoute
  '/settings/countries/edit/$id': typeof MainSettingsCountriesEditIdRoute
  '/settings/countries/show/$id': typeof MainSettingsCountriesShowIdRoute
  '/settings/shopify-stores/edit/$id': typeof MainSettingsShopifyStoresEditIdRoute
  '/settings/shopify-stores/show/$id': typeof MainSettingsShopifyStoresShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/_main/': typeof MainIndexRoute
  '/_main/attributes/add': typeof MainAttributesAddRoute
  '/_main/categories/add': typeof MainCategoriesAddRoute
  '/_main/coupons/add': typeof MainCouponsAddRoute
  '/_main/earning-rules/add': typeof MainEarningRulesAddRoute
  '/_main/faqs/add': typeof MainFaqsAddRoute
  '/_main/message-templates/add': typeof MainMessageTemplatesAddRoute
  '/_main/messages/send': typeof MainMessagesSendRoute
  '/_main/offers/add': typeof MainOffersAddRoute
  '/_main/products/add': typeof MainProductsAddRoute
  '/_main/rewards/add': typeof MainRewardsAddRoute
  '/_main/roles/add': typeof MainRolesAddRoute
  '/_main/show-rooms/add': typeof MainShowRoomsAddRoute
  '/_main/sliders/add': typeof MainSlidersAddRoute
  '/_main/static-pages/add': typeof MainStaticPagesAddRoute
  '/_main/supervisors/add': typeof MainSupervisorsAddRoute
  '/_main/tiers/add': typeof MainTiersAddRoute
  '/_main/admin-notifications/': typeof MainAdminNotificationsIndexRoute
  '/_main/attributes/': typeof MainAttributesIndexRoute
  '/_main/categories/': typeof MainCategoriesIndexRoute
  '/_main/coupons/': typeof MainCouponsIndexRoute
  '/_main/earning-rules/': typeof MainEarningRulesIndexRoute
  '/_main/exchanges/': typeof MainExchangesIndexRoute
  '/_main/faqs/': typeof MainFaqsIndexRoute
  '/_main/message-templates/': typeof MainMessageTemplatesIndexRoute
  '/_main/messages/': typeof MainMessagesIndexRoute
  '/_main/offers/': typeof MainOffersIndexRoute
  '/_main/orders/': typeof MainOrdersIndexRoute
  '/_main/payment-gateways/': typeof MainPaymentGatewaysIndexRoute
  '/_main/products/': typeof MainProductsIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/returns/': typeof MainReturnsIndexRoute
  '/_main/reviews/': typeof MainReviewsIndexRoute
  '/_main/rewards/': typeof MainRewardsIndexRoute
  '/_main/roles/': typeof MainRolesIndexRoute
  '/_main/show-rooms/': typeof MainShowRoomsIndexRoute
  '/_main/sliders/': typeof MainSlidersIndexRoute
  '/_main/sms-providers/': typeof MainSmsProvidersIndexRoute
  '/_main/static-pages/': typeof MainStaticPagesIndexRoute
  '/_main/supervisors/': typeof MainSupervisorsIndexRoute
  '/_main/tickets/': typeof MainTicketsIndexRoute
  '/_main/tiers/': typeof MainTiersIndexRoute
  '/_main/users/': typeof MainUsersIndexRoute
  '/_main/admin-notifications/show/$id': typeof MainAdminNotificationsShowIdRoute
  '/_main/attributes/edit/$id': typeof MainAttributesEditIdRoute
  '/_main/attributes/show/$id': typeof MainAttributesShowIdRoute
  '/_main/attributes/values/add': typeof MainAttributesValuesAddRoute
  '/_main/categories/edit/$id': typeof MainCategoriesEditIdRoute
  '/_main/categories/show/$id': typeof MainCategoriesShowIdRoute
  '/_main/coupons/edit/$id': typeof MainCouponsEditIdRoute
  '/_main/earning-rules/edit/$id': typeof MainEarningRulesEditIdRoute
  '/_main/faqs/edit/$id': typeof MainFaqsEditIdRoute
  '/_main/message-templates/edit/$id': typeof MainMessageTemplatesEditIdRoute
  '/_main/message-templates/show/$id': typeof MainMessageTemplatesShowIdRoute
  '/_main/messages/show/$id': typeof MainMessagesShowIdRoute
  '/_main/offers/edit/$id': typeof MainOffersEditIdRoute
  '/_main/orders/show/$id': typeof MainOrdersShowIdRoute
  '/_main/payment-gateways/sessions/$id': typeof MainPaymentGatewaysSessionsIdRoute
  '/_main/products/edit/$id': typeof MainProductsEditIdRoute
  '/_main/products/show/$id': typeof MainProductsShowIdRoute
  '/_main/reviews/show/$id': typeof MainReviewsShowIdRoute
  '/_main/rewards/edit/$id': typeof MainRewardsEditIdRoute
  '/_main/roles/edit/$id': typeof MainRolesEditIdRoute
  '/_main/roles/show/$id': typeof MainRolesShowIdRoute
  '/_main/settings/cities/add': typeof MainSettingsCitiesAddRoute
  '/_main/settings/countries/add': typeof MainSettingsCountriesAddRoute
  '/_main/settings/shopify-stores/add': typeof MainSettingsShopifyStoresAddRoute
  '/_main/show-rooms/edit/$id': typeof MainShowRoomsEditIdRoute
  '/_main/sliders/edit/$id': typeof MainSlidersEditIdRoute
  '/_main/sms-providers/sessions/$id': typeof MainSmsProvidersSessionsIdRoute
  '/_main/static-pages/edit/$id': typeof MainStaticPagesEditIdRoute
  '/_main/static-pages/show/$id': typeof MainStaticPagesShowIdRoute
  '/_main/supervisors/edit/$id': typeof MainSupervisorsEditIdRoute
  '/_main/tickets/show/$id': typeof MainTicketsShowIdRoute
  '/_main/tiers/edit/$id': typeof MainTiersEditIdRoute
  '/_main/users/show/$id': typeof MainUsersShowIdRoute
  '/_main/attributes/values/': typeof MainAttributesValuesIndexRoute
  '/_main/settings/cities/': typeof MainSettingsCitiesIndexRoute
  '/_main/settings/countries/': typeof MainSettingsCountriesIndexRoute
  '/_main/settings/general/': typeof MainSettingsGeneralIndexRoute
  '/_main/settings/notifications/': typeof MainSettingsNotificationsIndexRoute
  '/_main/settings/shopify-stores/': typeof MainSettingsShopifyStoresIndexRoute
  '/_main/attributes/values/edit/$id': typeof MainAttributesValuesEditIdRoute
  '/_main/settings/cities/edit/$id': typeof MainSettingsCitiesEditIdRoute
  '/_main/settings/countries/edit/$id': typeof MainSettingsCountriesEditIdRoute
  '/_main/settings/countries/show/$id': typeof MainSettingsCountriesShowIdRoute
  '/_main/settings/shopify-stores/edit/$id': typeof MainSettingsShopifyStoresEditIdRoute
  '/_main/settings/shopify-stores/show/$id': typeof MainSettingsShopifyStoresShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/auth/login'
    | '/attributes/add'
    | '/categories/add'
    | '/coupons/add'
    | '/earning-rules/add'
    | '/faqs/add'
    | '/message-templates/add'
    | '/messages/send'
    | '/offers/add'
    | '/products/add'
    | '/rewards/add'
    | '/roles/add'
    | '/show-rooms/add'
    | '/sliders/add'
    | '/static-pages/add'
    | '/supervisors/add'
    | '/tiers/add'
    | '/admin-notifications/'
    | '/attributes/'
    | '/categories/'
    | '/coupons/'
    | '/earning-rules/'
    | '/exchanges/'
    | '/faqs/'
    | '/message-templates/'
    | '/messages/'
    | '/offers/'
    | '/orders/'
    | '/payment-gateways/'
    | '/products/'
    | '/profile/'
    | '/returns/'
    | '/reviews/'
    | '/rewards/'
    | '/roles/'
    | '/show-rooms/'
    | '/sliders/'
    | '/sms-providers/'
    | '/static-pages/'
    | '/supervisors/'
    | '/tickets/'
    | '/tiers/'
    | '/users/'
    | '/admin-notifications/show/$id'
    | '/attributes/edit/$id'
    | '/attributes/show/$id'
    | '/attributes/values/add'
    | '/categories/edit/$id'
    | '/categories/show/$id'
    | '/coupons/edit/$id'
    | '/earning-rules/edit/$id'
    | '/faqs/edit/$id'
    | '/message-templates/edit/$id'
    | '/message-templates/show/$id'
    | '/messages/show/$id'
    | '/offers/edit/$id'
    | '/orders/show/$id'
    | '/payment-gateways/sessions/$id'
    | '/products/edit/$id'
    | '/products/show/$id'
    | '/reviews/show/$id'
    | '/rewards/edit/$id'
    | '/roles/edit/$id'
    | '/roles/show/$id'
    | '/settings/cities/add'
    | '/settings/countries/add'
    | '/settings/shopify-stores/add'
    | '/show-rooms/edit/$id'
    | '/sliders/edit/$id'
    | '/sms-providers/sessions/$id'
    | '/static-pages/edit/$id'
    | '/static-pages/show/$id'
    | '/supervisors/edit/$id'
    | '/tickets/show/$id'
    | '/tiers/edit/$id'
    | '/users/show/$id'
    | '/attributes/values/'
    | '/settings/cities/'
    | '/settings/countries/'
    | '/settings/general/'
    | '/settings/notifications/'
    | '/settings/shopify-stores/'
    | '/attributes/values/edit/$id'
    | '/settings/cities/edit/$id'
    | '/settings/countries/edit/$id'
    | '/settings/countries/show/$id'
    | '/settings/shopify-stores/edit/$id'
    | '/settings/shopify-stores/show/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/unauthorized'
    | '/auth/login'
    | '/'
    | '/attributes/add'
    | '/categories/add'
    | '/coupons/add'
    | '/earning-rules/add'
    | '/faqs/add'
    | '/message-templates/add'
    | '/messages/send'
    | '/offers/add'
    | '/products/add'
    | '/rewards/add'
    | '/roles/add'
    | '/show-rooms/add'
    | '/sliders/add'
    | '/static-pages/add'
    | '/supervisors/add'
    | '/tiers/add'
    | '/admin-notifications'
    | '/attributes'
    | '/categories'
    | '/coupons'
    | '/earning-rules'
    | '/exchanges'
    | '/faqs'
    | '/message-templates'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/payment-gateways'
    | '/products'
    | '/profile'
    | '/returns'
    | '/reviews'
    | '/rewards'
    | '/roles'
    | '/show-rooms'
    | '/sliders'
    | '/sms-providers'
    | '/static-pages'
    | '/supervisors'
    | '/tickets'
    | '/tiers'
    | '/users'
    | '/admin-notifications/show/$id'
    | '/attributes/edit/$id'
    | '/attributes/show/$id'
    | '/attributes/values/add'
    | '/categories/edit/$id'
    | '/categories/show/$id'
    | '/coupons/edit/$id'
    | '/earning-rules/edit/$id'
    | '/faqs/edit/$id'
    | '/message-templates/edit/$id'
    | '/message-templates/show/$id'
    | '/messages/show/$id'
    | '/offers/edit/$id'
    | '/orders/show/$id'
    | '/payment-gateways/sessions/$id'
    | '/products/edit/$id'
    | '/products/show/$id'
    | '/reviews/show/$id'
    | '/rewards/edit/$id'
    | '/roles/edit/$id'
    | '/roles/show/$id'
    | '/settings/cities/add'
    | '/settings/countries/add'
    | '/settings/shopify-stores/add'
    | '/show-rooms/edit/$id'
    | '/sliders/edit/$id'
    | '/sms-providers/sessions/$id'
    | '/static-pages/edit/$id'
    | '/static-pages/show/$id'
    | '/supervisors/edit/$id'
    | '/tickets/show/$id'
    | '/tiers/edit/$id'
    | '/users/show/$id'
    | '/attributes/values'
    | '/settings/cities'
    | '/settings/countries'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/shopify-stores'
    | '/attributes/values/edit/$id'
    | '/settings/cities/edit/$id'
    | '/settings/countries/edit/$id'
    | '/settings/countries/show/$id'
    | '/settings/shopify-stores/edit/$id'
    | '/settings/shopify-stores/show/$id'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/unauthorized'
    | '/auth/login'
    | '/_main/'
    | '/_main/attributes/add'
    | '/_main/categories/add'
    | '/_main/coupons/add'
    | '/_main/earning-rules/add'
    | '/_main/faqs/add'
    | '/_main/message-templates/add'
    | '/_main/messages/send'
    | '/_main/offers/add'
    | '/_main/products/add'
    | '/_main/rewards/add'
    | '/_main/roles/add'
    | '/_main/show-rooms/add'
    | '/_main/sliders/add'
    | '/_main/static-pages/add'
    | '/_main/supervisors/add'
    | '/_main/tiers/add'
    | '/_main/admin-notifications/'
    | '/_main/attributes/'
    | '/_main/categories/'
    | '/_main/coupons/'
    | '/_main/earning-rules/'
    | '/_main/exchanges/'
    | '/_main/faqs/'
    | '/_main/message-templates/'
    | '/_main/messages/'
    | '/_main/offers/'
    | '/_main/orders/'
    | '/_main/payment-gateways/'
    | '/_main/products/'
    | '/_main/profile/'
    | '/_main/returns/'
    | '/_main/reviews/'
    | '/_main/rewards/'
    | '/_main/roles/'
    | '/_main/show-rooms/'
    | '/_main/sliders/'
    | '/_main/sms-providers/'
    | '/_main/static-pages/'
    | '/_main/supervisors/'
    | '/_main/tickets/'
    | '/_main/tiers/'
    | '/_main/users/'
    | '/_main/admin-notifications/show/$id'
    | '/_main/attributes/edit/$id'
    | '/_main/attributes/show/$id'
    | '/_main/attributes/values/add'
    | '/_main/categories/edit/$id'
    | '/_main/categories/show/$id'
    | '/_main/coupons/edit/$id'
    | '/_main/earning-rules/edit/$id'
    | '/_main/faqs/edit/$id'
    | '/_main/message-templates/edit/$id'
    | '/_main/message-templates/show/$id'
    | '/_main/messages/show/$id'
    | '/_main/offers/edit/$id'
    | '/_main/orders/show/$id'
    | '/_main/payment-gateways/sessions/$id'
    | '/_main/products/edit/$id'
    | '/_main/products/show/$id'
    | '/_main/reviews/show/$id'
    | '/_main/rewards/edit/$id'
    | '/_main/roles/edit/$id'
    | '/_main/roles/show/$id'
    | '/_main/settings/cities/add'
    | '/_main/settings/countries/add'
    | '/_main/settings/shopify-stores/add'
    | '/_main/show-rooms/edit/$id'
    | '/_main/sliders/edit/$id'
    | '/_main/sms-providers/sessions/$id'
    | '/_main/static-pages/edit/$id'
    | '/_main/static-pages/show/$id'
    | '/_main/supervisors/edit/$id'
    | '/_main/tickets/show/$id'
    | '/_main/tiers/edit/$id'
    | '/_main/users/show/$id'
    | '/_main/attributes/values/'
    | '/_main/settings/cities/'
    | '/_main/settings/countries/'
    | '/_main/settings/general/'
    | '/_main/settings/notifications/'
    | '/_main/settings/shopify-stores/'
    | '/_main/attributes/values/edit/$id'
    | '/_main/settings/cities/edit/$id'
    | '/_main/settings/countries/edit/$id'
    | '/_main/settings/countries/show/$id'
    | '/_main/settings/shopify-stores/edit/$id'
    | '/_main/settings/shopify-stores/show/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/users/': {
      id: '/_main/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof MainUsersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tiers/': {
      id: '/_main/tiers/'
      path: '/tiers'
      fullPath: '/tiers/'
      preLoaderRoute: typeof MainTiersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tickets/': {
      id: '/_main/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof MainTicketsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/supervisors/': {
      id: '/_main/supervisors/'
      path: '/supervisors'
      fullPath: '/supervisors/'
      preLoaderRoute: typeof MainSupervisorsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/static-pages/': {
      id: '/_main/static-pages/'
      path: '/static-pages'
      fullPath: '/static-pages/'
      preLoaderRoute: typeof MainStaticPagesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/sms-providers/': {
      id: '/_main/sms-providers/'
      path: '/sms-providers'
      fullPath: '/sms-providers/'
      preLoaderRoute: typeof MainSmsProvidersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/sliders/': {
      id: '/_main/sliders/'
      path: '/sliders'
      fullPath: '/sliders/'
      preLoaderRoute: typeof MainSlidersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/show-rooms/': {
      id: '/_main/show-rooms/'
      path: '/show-rooms'
      fullPath: '/show-rooms/'
      preLoaderRoute: typeof MainShowRoomsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/roles/': {
      id: '/_main/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof MainRolesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/rewards/': {
      id: '/_main/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof MainRewardsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reviews/': {
      id: '/_main/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof MainReviewsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/returns/': {
      id: '/_main/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof MainReturnsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products/': {
      id: '/_main/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof MainProductsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/payment-gateways/': {
      id: '/_main/payment-gateways/'
      path: '/payment-gateways'
      fullPath: '/payment-gateways/'
      preLoaderRoute: typeof MainPaymentGatewaysIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/orders/': {
      id: '/_main/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof MainOrdersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/offers/': {
      id: '/_main/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof MainOffersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/messages/': {
      id: '/_main/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MainMessagesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/message-templates/': {
      id: '/_main/message-templates/'
      path: '/message-templates'
      fullPath: '/message-templates/'
      preLoaderRoute: typeof MainMessageTemplatesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/faqs/': {
      id: '/_main/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof MainFaqsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/exchanges/': {
      id: '/_main/exchanges/'
      path: '/exchanges'
      fullPath: '/exchanges/'
      preLoaderRoute: typeof MainExchangesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/earning-rules/': {
      id: '/_main/earning-rules/'
      path: '/earning-rules'
      fullPath: '/earning-rules/'
      preLoaderRoute: typeof MainEarningRulesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/coupons/': {
      id: '/_main/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof MainCouponsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories/': {
      id: '/_main/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof MainCategoriesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/': {
      id: '/_main/attributes/'
      path: '/attributes'
      fullPath: '/attributes/'
      preLoaderRoute: typeof MainAttributesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin-notifications/': {
      id: '/_main/admin-notifications/'
      path: '/admin-notifications'
      fullPath: '/admin-notifications/'
      preLoaderRoute: typeof MainAdminNotificationsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tiers/add': {
      id: '/_main/tiers/add'
      path: '/tiers/add'
      fullPath: '/tiers/add'
      preLoaderRoute: typeof MainTiersAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/supervisors/add': {
      id: '/_main/supervisors/add'
      path: '/supervisors/add'
      fullPath: '/supervisors/add'
      preLoaderRoute: typeof MainSupervisorsAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/static-pages/add': {
      id: '/_main/static-pages/add'
      path: '/static-pages/add'
      fullPath: '/static-pages/add'
      preLoaderRoute: typeof MainStaticPagesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/sliders/add': {
      id: '/_main/sliders/add'
      path: '/sliders/add'
      fullPath: '/sliders/add'
      preLoaderRoute: typeof MainSlidersAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/show-rooms/add': {
      id: '/_main/show-rooms/add'
      path: '/show-rooms/add'
      fullPath: '/show-rooms/add'
      preLoaderRoute: typeof MainShowRoomsAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/roles/add': {
      id: '/_main/roles/add'
      path: '/roles/add'
      fullPath: '/roles/add'
      preLoaderRoute: typeof MainRolesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/rewards/add': {
      id: '/_main/rewards/add'
      path: '/rewards/add'
      fullPath: '/rewards/add'
      preLoaderRoute: typeof MainRewardsAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products/add': {
      id: '/_main/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof MainProductsAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/offers/add': {
      id: '/_main/offers/add'
      path: '/offers/add'
      fullPath: '/offers/add'
      preLoaderRoute: typeof MainOffersAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/messages/send': {
      id: '/_main/messages/send'
      path: '/messages/send'
      fullPath: '/messages/send'
      preLoaderRoute: typeof MainMessagesSendRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/message-templates/add': {
      id: '/_main/message-templates/add'
      path: '/message-templates/add'
      fullPath: '/message-templates/add'
      preLoaderRoute: typeof MainMessageTemplatesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/faqs/add': {
      id: '/_main/faqs/add'
      path: '/faqs/add'
      fullPath: '/faqs/add'
      preLoaderRoute: typeof MainFaqsAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/earning-rules/add': {
      id: '/_main/earning-rules/add'
      path: '/earning-rules/add'
      fullPath: '/earning-rules/add'
      preLoaderRoute: typeof MainEarningRulesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/coupons/add': {
      id: '/_main/coupons/add'
      path: '/coupons/add'
      fullPath: '/coupons/add'
      preLoaderRoute: typeof MainCouponsAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories/add': {
      id: '/_main/categories/add'
      path: '/categories/add'
      fullPath: '/categories/add'
      preLoaderRoute: typeof MainCategoriesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/add': {
      id: '/_main/attributes/add'
      path: '/attributes/add'
      fullPath: '/attributes/add'
      preLoaderRoute: typeof MainAttributesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/shopify-stores/': {
      id: '/_main/settings/shopify-stores/'
      path: '/settings/shopify-stores'
      fullPath: '/settings/shopify-stores/'
      preLoaderRoute: typeof MainSettingsShopifyStoresIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/notifications/': {
      id: '/_main/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof MainSettingsNotificationsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/general/': {
      id: '/_main/settings/general/'
      path: '/settings/general'
      fullPath: '/settings/general/'
      preLoaderRoute: typeof MainSettingsGeneralIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/countries/': {
      id: '/_main/settings/countries/'
      path: '/settings/countries'
      fullPath: '/settings/countries/'
      preLoaderRoute: typeof MainSettingsCountriesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/cities/': {
      id: '/_main/settings/cities/'
      path: '/settings/cities'
      fullPath: '/settings/cities/'
      preLoaderRoute: typeof MainSettingsCitiesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/values/': {
      id: '/_main/attributes/values/'
      path: '/attributes/values'
      fullPath: '/attributes/values/'
      preLoaderRoute: typeof MainAttributesValuesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users/show/$id': {
      id: '/_main/users/show/$id'
      path: '/users/show/$id'
      fullPath: '/users/show/$id'
      preLoaderRoute: typeof MainUsersShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tiers/edit/$id': {
      id: '/_main/tiers/edit/$id'
      path: '/tiers/edit/$id'
      fullPath: '/tiers/edit/$id'
      preLoaderRoute: typeof MainTiersEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tickets/show/$id': {
      id: '/_main/tickets/show/$id'
      path: '/tickets/show/$id'
      fullPath: '/tickets/show/$id'
      preLoaderRoute: typeof MainTicketsShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/supervisors/edit/$id': {
      id: '/_main/supervisors/edit/$id'
      path: '/supervisors/edit/$id'
      fullPath: '/supervisors/edit/$id'
      preLoaderRoute: typeof MainSupervisorsEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/static-pages/show/$id': {
      id: '/_main/static-pages/show/$id'
      path: '/static-pages/show/$id'
      fullPath: '/static-pages/show/$id'
      preLoaderRoute: typeof MainStaticPagesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/static-pages/edit/$id': {
      id: '/_main/static-pages/edit/$id'
      path: '/static-pages/edit/$id'
      fullPath: '/static-pages/edit/$id'
      preLoaderRoute: typeof MainStaticPagesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/sms-providers/sessions/$id': {
      id: '/_main/sms-providers/sessions/$id'
      path: '/sms-providers/sessions/$id'
      fullPath: '/sms-providers/sessions/$id'
      preLoaderRoute: typeof MainSmsProvidersSessionsIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/sliders/edit/$id': {
      id: '/_main/sliders/edit/$id'
      path: '/sliders/edit/$id'
      fullPath: '/sliders/edit/$id'
      preLoaderRoute: typeof MainSlidersEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/show-rooms/edit/$id': {
      id: '/_main/show-rooms/edit/$id'
      path: '/show-rooms/edit/$id'
      fullPath: '/show-rooms/edit/$id'
      preLoaderRoute: typeof MainShowRoomsEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/shopify-stores/add': {
      id: '/_main/settings/shopify-stores/add'
      path: '/settings/shopify-stores/add'
      fullPath: '/settings/shopify-stores/add'
      preLoaderRoute: typeof MainSettingsShopifyStoresAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/countries/add': {
      id: '/_main/settings/countries/add'
      path: '/settings/countries/add'
      fullPath: '/settings/countries/add'
      preLoaderRoute: typeof MainSettingsCountriesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/cities/add': {
      id: '/_main/settings/cities/add'
      path: '/settings/cities/add'
      fullPath: '/settings/cities/add'
      preLoaderRoute: typeof MainSettingsCitiesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/roles/show/$id': {
      id: '/_main/roles/show/$id'
      path: '/roles/show/$id'
      fullPath: '/roles/show/$id'
      preLoaderRoute: typeof MainRolesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/roles/edit/$id': {
      id: '/_main/roles/edit/$id'
      path: '/roles/edit/$id'
      fullPath: '/roles/edit/$id'
      preLoaderRoute: typeof MainRolesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/rewards/edit/$id': {
      id: '/_main/rewards/edit/$id'
      path: '/rewards/edit/$id'
      fullPath: '/rewards/edit/$id'
      preLoaderRoute: typeof MainRewardsEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reviews/show/$id': {
      id: '/_main/reviews/show/$id'
      path: '/reviews/show/$id'
      fullPath: '/reviews/show/$id'
      preLoaderRoute: typeof MainReviewsShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products/show/$id': {
      id: '/_main/products/show/$id'
      path: '/products/show/$id'
      fullPath: '/products/show/$id'
      preLoaderRoute: typeof MainProductsShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products/edit/$id': {
      id: '/_main/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof MainProductsEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/payment-gateways/sessions/$id': {
      id: '/_main/payment-gateways/sessions/$id'
      path: '/payment-gateways/sessions/$id'
      fullPath: '/payment-gateways/sessions/$id'
      preLoaderRoute: typeof MainPaymentGatewaysSessionsIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/orders/show/$id': {
      id: '/_main/orders/show/$id'
      path: '/orders/show/$id'
      fullPath: '/orders/show/$id'
      preLoaderRoute: typeof MainOrdersShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/offers/edit/$id': {
      id: '/_main/offers/edit/$id'
      path: '/offers/edit/$id'
      fullPath: '/offers/edit/$id'
      preLoaderRoute: typeof MainOffersEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/messages/show/$id': {
      id: '/_main/messages/show/$id'
      path: '/messages/show/$id'
      fullPath: '/messages/show/$id'
      preLoaderRoute: typeof MainMessagesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/message-templates/show/$id': {
      id: '/_main/message-templates/show/$id'
      path: '/message-templates/show/$id'
      fullPath: '/message-templates/show/$id'
      preLoaderRoute: typeof MainMessageTemplatesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/message-templates/edit/$id': {
      id: '/_main/message-templates/edit/$id'
      path: '/message-templates/edit/$id'
      fullPath: '/message-templates/edit/$id'
      preLoaderRoute: typeof MainMessageTemplatesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/faqs/edit/$id': {
      id: '/_main/faqs/edit/$id'
      path: '/faqs/edit/$id'
      fullPath: '/faqs/edit/$id'
      preLoaderRoute: typeof MainFaqsEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/earning-rules/edit/$id': {
      id: '/_main/earning-rules/edit/$id'
      path: '/earning-rules/edit/$id'
      fullPath: '/earning-rules/edit/$id'
      preLoaderRoute: typeof MainEarningRulesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/coupons/edit/$id': {
      id: '/_main/coupons/edit/$id'
      path: '/coupons/edit/$id'
      fullPath: '/coupons/edit/$id'
      preLoaderRoute: typeof MainCouponsEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories/show/$id': {
      id: '/_main/categories/show/$id'
      path: '/categories/show/$id'
      fullPath: '/categories/show/$id'
      preLoaderRoute: typeof MainCategoriesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories/edit/$id': {
      id: '/_main/categories/edit/$id'
      path: '/categories/edit/$id'
      fullPath: '/categories/edit/$id'
      preLoaderRoute: typeof MainCategoriesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/values/add': {
      id: '/_main/attributes/values/add'
      path: '/attributes/values/add'
      fullPath: '/attributes/values/add'
      preLoaderRoute: typeof MainAttributesValuesAddRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/show/$id': {
      id: '/_main/attributes/show/$id'
      path: '/attributes/show/$id'
      fullPath: '/attributes/show/$id'
      preLoaderRoute: typeof MainAttributesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/edit/$id': {
      id: '/_main/attributes/edit/$id'
      path: '/attributes/edit/$id'
      fullPath: '/attributes/edit/$id'
      preLoaderRoute: typeof MainAttributesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin-notifications/show/$id': {
      id: '/_main/admin-notifications/show/$id'
      path: '/admin-notifications/show/$id'
      fullPath: '/admin-notifications/show/$id'
      preLoaderRoute: typeof MainAdminNotificationsShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/shopify-stores/show/$id': {
      id: '/_main/settings/shopify-stores/show/$id'
      path: '/settings/shopify-stores/show/$id'
      fullPath: '/settings/shopify-stores/show/$id'
      preLoaderRoute: typeof MainSettingsShopifyStoresShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/shopify-stores/edit/$id': {
      id: '/_main/settings/shopify-stores/edit/$id'
      path: '/settings/shopify-stores/edit/$id'
      fullPath: '/settings/shopify-stores/edit/$id'
      preLoaderRoute: typeof MainSettingsShopifyStoresEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/countries/show/$id': {
      id: '/_main/settings/countries/show/$id'
      path: '/settings/countries/show/$id'
      fullPath: '/settings/countries/show/$id'
      preLoaderRoute: typeof MainSettingsCountriesShowIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/countries/edit/$id': {
      id: '/_main/settings/countries/edit/$id'
      path: '/settings/countries/edit/$id'
      fullPath: '/settings/countries/edit/$id'
      preLoaderRoute: typeof MainSettingsCountriesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/cities/edit/$id': {
      id: '/_main/settings/cities/edit/$id'
      path: '/settings/cities/edit/$id'
      fullPath: '/settings/cities/edit/$id'
      preLoaderRoute: typeof MainSettingsCitiesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/attributes/values/edit/$id': {
      id: '/_main/attributes/values/edit/$id'
      path: '/attributes/values/edit/$id'
      fullPath: '/attributes/values/edit/$id'
      preLoaderRoute: typeof MainAttributesValuesEditIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAttributesAddRoute: typeof MainAttributesAddRoute
  MainCategoriesAddRoute: typeof MainCategoriesAddRoute
  MainCouponsAddRoute: typeof MainCouponsAddRoute
  MainEarningRulesAddRoute: typeof MainEarningRulesAddRoute
  MainFaqsAddRoute: typeof MainFaqsAddRoute
  MainMessageTemplatesAddRoute: typeof MainMessageTemplatesAddRoute
  MainMessagesSendRoute: typeof MainMessagesSendRoute
  MainOffersAddRoute: typeof MainOffersAddRoute
  MainProductsAddRoute: typeof MainProductsAddRoute
  MainRewardsAddRoute: typeof MainRewardsAddRoute
  MainRolesAddRoute: typeof MainRolesAddRoute
  MainShowRoomsAddRoute: typeof MainShowRoomsAddRoute
  MainSlidersAddRoute: typeof MainSlidersAddRoute
  MainStaticPagesAddRoute: typeof MainStaticPagesAddRoute
  MainSupervisorsAddRoute: typeof MainSupervisorsAddRoute
  MainTiersAddRoute: typeof MainTiersAddRoute
  MainAdminNotificationsIndexRoute: typeof MainAdminNotificationsIndexRoute
  MainAttributesIndexRoute: typeof MainAttributesIndexRoute
  MainCategoriesIndexRoute: typeof MainCategoriesIndexRoute
  MainCouponsIndexRoute: typeof MainCouponsIndexRoute
  MainEarningRulesIndexRoute: typeof MainEarningRulesIndexRoute
  MainExchangesIndexRoute: typeof MainExchangesIndexRoute
  MainFaqsIndexRoute: typeof MainFaqsIndexRoute
  MainMessageTemplatesIndexRoute: typeof MainMessageTemplatesIndexRoute
  MainMessagesIndexRoute: typeof MainMessagesIndexRoute
  MainOffersIndexRoute: typeof MainOffersIndexRoute
  MainOrdersIndexRoute: typeof MainOrdersIndexRoute
  MainPaymentGatewaysIndexRoute: typeof MainPaymentGatewaysIndexRoute
  MainProductsIndexRoute: typeof MainProductsIndexRoute
  MainProfileIndexRoute: typeof MainProfileIndexRoute
  MainReturnsIndexRoute: typeof MainReturnsIndexRoute
  MainReviewsIndexRoute: typeof MainReviewsIndexRoute
  MainRewardsIndexRoute: typeof MainRewardsIndexRoute
  MainRolesIndexRoute: typeof MainRolesIndexRoute
  MainShowRoomsIndexRoute: typeof MainShowRoomsIndexRoute
  MainSlidersIndexRoute: typeof MainSlidersIndexRoute
  MainSmsProvidersIndexRoute: typeof MainSmsProvidersIndexRoute
  MainStaticPagesIndexRoute: typeof MainStaticPagesIndexRoute
  MainSupervisorsIndexRoute: typeof MainSupervisorsIndexRoute
  MainTicketsIndexRoute: typeof MainTicketsIndexRoute
  MainTiersIndexRoute: typeof MainTiersIndexRoute
  MainUsersIndexRoute: typeof MainUsersIndexRoute
  MainAdminNotificationsShowIdRoute: typeof MainAdminNotificationsShowIdRoute
  MainAttributesEditIdRoute: typeof MainAttributesEditIdRoute
  MainAttributesShowIdRoute: typeof MainAttributesShowIdRoute
  MainAttributesValuesAddRoute: typeof MainAttributesValuesAddRoute
  MainCategoriesEditIdRoute: typeof MainCategoriesEditIdRoute
  MainCategoriesShowIdRoute: typeof MainCategoriesShowIdRoute
  MainCouponsEditIdRoute: typeof MainCouponsEditIdRoute
  MainEarningRulesEditIdRoute: typeof MainEarningRulesEditIdRoute
  MainFaqsEditIdRoute: typeof MainFaqsEditIdRoute
  MainMessageTemplatesEditIdRoute: typeof MainMessageTemplatesEditIdRoute
  MainMessageTemplatesShowIdRoute: typeof MainMessageTemplatesShowIdRoute
  MainMessagesShowIdRoute: typeof MainMessagesShowIdRoute
  MainOffersEditIdRoute: typeof MainOffersEditIdRoute
  MainOrdersShowIdRoute: typeof MainOrdersShowIdRoute
  MainPaymentGatewaysSessionsIdRoute: typeof MainPaymentGatewaysSessionsIdRoute
  MainProductsEditIdRoute: typeof MainProductsEditIdRoute
  MainProductsShowIdRoute: typeof MainProductsShowIdRoute
  MainReviewsShowIdRoute: typeof MainReviewsShowIdRoute
  MainRewardsEditIdRoute: typeof MainRewardsEditIdRoute
  MainRolesEditIdRoute: typeof MainRolesEditIdRoute
  MainRolesShowIdRoute: typeof MainRolesShowIdRoute
  MainSettingsCitiesAddRoute: typeof MainSettingsCitiesAddRoute
  MainSettingsCountriesAddRoute: typeof MainSettingsCountriesAddRoute
  MainSettingsShopifyStoresAddRoute: typeof MainSettingsShopifyStoresAddRoute
  MainShowRoomsEditIdRoute: typeof MainShowRoomsEditIdRoute
  MainSlidersEditIdRoute: typeof MainSlidersEditIdRoute
  MainSmsProvidersSessionsIdRoute: typeof MainSmsProvidersSessionsIdRoute
  MainStaticPagesEditIdRoute: typeof MainStaticPagesEditIdRoute
  MainStaticPagesShowIdRoute: typeof MainStaticPagesShowIdRoute
  MainSupervisorsEditIdRoute: typeof MainSupervisorsEditIdRoute
  MainTicketsShowIdRoute: typeof MainTicketsShowIdRoute
  MainTiersEditIdRoute: typeof MainTiersEditIdRoute
  MainUsersShowIdRoute: typeof MainUsersShowIdRoute
  MainAttributesValuesIndexRoute: typeof MainAttributesValuesIndexRoute
  MainSettingsCitiesIndexRoute: typeof MainSettingsCitiesIndexRoute
  MainSettingsCountriesIndexRoute: typeof MainSettingsCountriesIndexRoute
  MainSettingsGeneralIndexRoute: typeof MainSettingsGeneralIndexRoute
  MainSettingsNotificationsIndexRoute: typeof MainSettingsNotificationsIndexRoute
  MainSettingsShopifyStoresIndexRoute: typeof MainSettingsShopifyStoresIndexRoute
  MainAttributesValuesEditIdRoute: typeof MainAttributesValuesEditIdRoute
  MainSettingsCitiesEditIdRoute: typeof MainSettingsCitiesEditIdRoute
  MainSettingsCountriesEditIdRoute: typeof MainSettingsCountriesEditIdRoute
  MainSettingsCountriesShowIdRoute: typeof MainSettingsCountriesShowIdRoute
  MainSettingsShopifyStoresEditIdRoute: typeof MainSettingsShopifyStoresEditIdRoute
  MainSettingsShopifyStoresShowIdRoute: typeof MainSettingsShopifyStoresShowIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAttributesAddRoute: MainAttributesAddRoute,
  MainCategoriesAddRoute: MainCategoriesAddRoute,
  MainCouponsAddRoute: MainCouponsAddRoute,
  MainEarningRulesAddRoute: MainEarningRulesAddRoute,
  MainFaqsAddRoute: MainFaqsAddRoute,
  MainMessageTemplatesAddRoute: MainMessageTemplatesAddRoute,
  MainMessagesSendRoute: MainMessagesSendRoute,
  MainOffersAddRoute: MainOffersAddRoute,
  MainProductsAddRoute: MainProductsAddRoute,
  MainRewardsAddRoute: MainRewardsAddRoute,
  MainRolesAddRoute: MainRolesAddRoute,
  MainShowRoomsAddRoute: MainShowRoomsAddRoute,
  MainSlidersAddRoute: MainSlidersAddRoute,
  MainStaticPagesAddRoute: MainStaticPagesAddRoute,
  MainSupervisorsAddRoute: MainSupervisorsAddRoute,
  MainTiersAddRoute: MainTiersAddRoute,
  MainAdminNotificationsIndexRoute: MainAdminNotificationsIndexRoute,
  MainAttributesIndexRoute: MainAttributesIndexRoute,
  MainCategoriesIndexRoute: MainCategoriesIndexRoute,
  MainCouponsIndexRoute: MainCouponsIndexRoute,
  MainEarningRulesIndexRoute: MainEarningRulesIndexRoute,
  MainExchangesIndexRoute: MainExchangesIndexRoute,
  MainFaqsIndexRoute: MainFaqsIndexRoute,
  MainMessageTemplatesIndexRoute: MainMessageTemplatesIndexRoute,
  MainMessagesIndexRoute: MainMessagesIndexRoute,
  MainOffersIndexRoute: MainOffersIndexRoute,
  MainOrdersIndexRoute: MainOrdersIndexRoute,
  MainPaymentGatewaysIndexRoute: MainPaymentGatewaysIndexRoute,
  MainProductsIndexRoute: MainProductsIndexRoute,
  MainProfileIndexRoute: MainProfileIndexRoute,
  MainReturnsIndexRoute: MainReturnsIndexRoute,
  MainReviewsIndexRoute: MainReviewsIndexRoute,
  MainRewardsIndexRoute: MainRewardsIndexRoute,
  MainRolesIndexRoute: MainRolesIndexRoute,
  MainShowRoomsIndexRoute: MainShowRoomsIndexRoute,
  MainSlidersIndexRoute: MainSlidersIndexRoute,
  MainSmsProvidersIndexRoute: MainSmsProvidersIndexRoute,
  MainStaticPagesIndexRoute: MainStaticPagesIndexRoute,
  MainSupervisorsIndexRoute: MainSupervisorsIndexRoute,
  MainTicketsIndexRoute: MainTicketsIndexRoute,
  MainTiersIndexRoute: MainTiersIndexRoute,
  MainUsersIndexRoute: MainUsersIndexRoute,
  MainAdminNotificationsShowIdRoute: MainAdminNotificationsShowIdRoute,
  MainAttributesEditIdRoute: MainAttributesEditIdRoute,
  MainAttributesShowIdRoute: MainAttributesShowIdRoute,
  MainAttributesValuesAddRoute: MainAttributesValuesAddRoute,
  MainCategoriesEditIdRoute: MainCategoriesEditIdRoute,
  MainCategoriesShowIdRoute: MainCategoriesShowIdRoute,
  MainCouponsEditIdRoute: MainCouponsEditIdRoute,
  MainEarningRulesEditIdRoute: MainEarningRulesEditIdRoute,
  MainFaqsEditIdRoute: MainFaqsEditIdRoute,
  MainMessageTemplatesEditIdRoute: MainMessageTemplatesEditIdRoute,
  MainMessageTemplatesShowIdRoute: MainMessageTemplatesShowIdRoute,
  MainMessagesShowIdRoute: MainMessagesShowIdRoute,
  MainOffersEditIdRoute: MainOffersEditIdRoute,
  MainOrdersShowIdRoute: MainOrdersShowIdRoute,
  MainPaymentGatewaysSessionsIdRoute: MainPaymentGatewaysSessionsIdRoute,
  MainProductsEditIdRoute: MainProductsEditIdRoute,
  MainProductsShowIdRoute: MainProductsShowIdRoute,
  MainReviewsShowIdRoute: MainReviewsShowIdRoute,
  MainRewardsEditIdRoute: MainRewardsEditIdRoute,
  MainRolesEditIdRoute: MainRolesEditIdRoute,
  MainRolesShowIdRoute: MainRolesShowIdRoute,
  MainSettingsCitiesAddRoute: MainSettingsCitiesAddRoute,
  MainSettingsCountriesAddRoute: MainSettingsCountriesAddRoute,
  MainSettingsShopifyStoresAddRoute: MainSettingsShopifyStoresAddRoute,
  MainShowRoomsEditIdRoute: MainShowRoomsEditIdRoute,
  MainSlidersEditIdRoute: MainSlidersEditIdRoute,
  MainSmsProvidersSessionsIdRoute: MainSmsProvidersSessionsIdRoute,
  MainStaticPagesEditIdRoute: MainStaticPagesEditIdRoute,
  MainStaticPagesShowIdRoute: MainStaticPagesShowIdRoute,
  MainSupervisorsEditIdRoute: MainSupervisorsEditIdRoute,
  MainTicketsShowIdRoute: MainTicketsShowIdRoute,
  MainTiersEditIdRoute: MainTiersEditIdRoute,
  MainUsersShowIdRoute: MainUsersShowIdRoute,
  MainAttributesValuesIndexRoute: MainAttributesValuesIndexRoute,
  MainSettingsCitiesIndexRoute: MainSettingsCitiesIndexRoute,
  MainSettingsCountriesIndexRoute: MainSettingsCountriesIndexRoute,
  MainSettingsGeneralIndexRoute: MainSettingsGeneralIndexRoute,
  MainSettingsNotificationsIndexRoute: MainSettingsNotificationsIndexRoute,
  MainSettingsShopifyStoresIndexRoute: MainSettingsShopifyStoresIndexRoute,
  MainAttributesValuesEditIdRoute: MainAttributesValuesEditIdRoute,
  MainSettingsCitiesEditIdRoute: MainSettingsCitiesEditIdRoute,
  MainSettingsCountriesEditIdRoute: MainSettingsCountriesEditIdRoute,
  MainSettingsCountriesShowIdRoute: MainSettingsCountriesShowIdRoute,
  MainSettingsShopifyStoresEditIdRoute: MainSettingsShopifyStoresEditIdRoute,
  MainSettingsShopifyStoresShowIdRoute: MainSettingsShopifyStoresShowIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
